name: publish-api-documentation

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    tags:
      - v3.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install GNS3 server
      run: |
        python setup.py install
    - name: Generate the API documentation
      run: |
        cd scripts
        python3 publish_api_documentation.py
    - name: Publish the API documentation
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout gh-pages
        git add docs
        git status
        git commit -m "Publish API documentation"
        git push
